using System;
using System.Collections.Generic;

namespace mowt_myst_gen
{
    internal static class Data
    {
        private static IList<string> Location = new string[]
        {
            "Club nocturno",
"Volcán de la Isla",
"Castillo Europeo",
"Campanario",
"Pantano",
"Parque Nacional",
"Iglesia",
"Comunidad agrícola del Medio Oeste",
"Badlands de Nuevo México",
"Cavernas",
"Parque acuático",
"Ruta 66",
"Alcantarillas",
"Estación espacial",
"Centro comercial",
"Cabaña en el bosque",
"Chernobyl",
"Casa Blanca",
"Tundra ártica",
"Suburbio de clase alta",
"Comisaría de un pueblo pequeño",
"Zona urbana sórdida",
"Campings",
"Tren",
"Prisión",
"Pueblo fantasma",
"Stonehenge",
"Lugar de culto",
"Faro",
"Camino rural",
"Plaza del Tiempo",
"Infierno",
"Escondite del asesino en serie",
"Edificio de apartamentos abandonado",
"Gran Cañón",
"Estación de radio nocturna",
"Espectáculo de fenómenos",
"Mazmorra",
"Sermón religioso emergente",
"Vieja mina",
"Plataforma de perforación en alta mar",
"Hospital",
"Colinas irlandesas",
"Carnaval itinerante",
"Sitio secreto del gobierno",
"Yate en el mar",
"Campus universitario",
"Antiguo puente cubierto",
"Estadio de fútbol",
"Huerto sospechoso",
"Antigua mansión",
"Casa embrujada",
"Restaurante de carretera",
"Cementerio",
"Triángulo de las Bermudas",
"Ciudad costera de Nueva Inglaterra",
"Campamento militar de primera línea",
"Mundo de los tragos",
"Reserva de nativos americanos",
"Centro de investigación",
"Ciudad de Riverside",
"Coordenadas anodinas",
"Motel",
"Pueblo pesquero",
"Casa de la Fraternidad",
"Gruta del Cenote",
"Isla subdesarrollada",
"Altar de sacrificio al aire libre",
"Cripta templaria",
"Complejo de la isla de Ritzy",
"Catacumbas",
"Selva sudamericana",
"Ciudad de la playa",
"Portal interdimensional",
"Cabaña junto al lago",
"Cueva submarina",
"Pueblo extrañamente pintoresco",
"Granja aislada",
"Banco",
"Jardín Botánico",
"Laberinto de setos",
"Gasolinera de carretera",
"Bosque Fey",
"Antiguo manicomio",
"Avión de pasajeros",
"Comunidad lacustre",
"Sitio sagrado",
"Bosque de los Apalaches",
"Barco fantasma",
"Campo de maíz",
"Montañas Rocosas de Colorado",
"Centro médico en cuarentena",
"Sala de cine",
"Desierto",
"Escuela secundaria",
"Bar de la ciudad",
"Sitio de invocación demoníaca",
"Pueblo Europeo de Pascua",
"Fábrica industrial",
"Noroeste del Pacífico",
        };

        private static IList<string> Monster = new string[]
        {
            "Dopplegangers",
"Deidad",
"Arachnae",
"Vikingos",
"Sirena",
"Poltergeist",
"Payaso asesino",
"Mutantes de la colina",
"Chupacabra",
"Kitsune",
"El hombre mosca de Cronenberg",
"Dr. Moreau",
"Graboides",
"Hombres serpiente",
"Quimera",
"Muñeca poseída",
"Duendes",
"Asesino de pesadillas (Freddy)",
"Reaper",
"Sirena",
"Gárgola",
"Zombies",
"Monstruo del mar",
"Predicador",
"Monstruo de la caja de pájaros",
"Espíritu ahogado",
"Robots",
"Bruja",
"Hechicero",
"Virus de la locura",
"Niño poseso/demónico",
"Dios griego",
"Enjambre de insectos mortales",
"Dama de Blanco (Espíritu)",
"Alienígena",
"Minotauro",
"Vendedor",
"Monstruo del árbol",
"Casa poseída",
"Fénix",
"Murciélago Dragón",
"Fantasma",
"Mothman",
"Skinwalker",
"Jinete sin cabeza",
"Leshy",
"La Cosa",
"Abyzou (hada de los sueños)",
"Depredador",
"Espantapájaros",
"Ángeles llorones",
"Hombre lobo",
"Yeti",
"Wendigo",
"Esfinge",
"Troll",
"Abominación",
"Espectros apaches",
"Thunderbird",
"banshee",
"Slenderman",
"Golem",
"Hombre Invisible",
"Hambre",
"Silencio (Dr. Who)",
"Oni",
"Demonio",
"Gremlins",
"Animales poseídos",
"Asesino en serie",
"Gigante",
"Criatura del pantano",
"Changeling",
"Acheri",
"Elemental de agua",
"Ángel",
"Stepfords",
"Vampiro",
"Xenomorfo",
"Sátiro",
"Súcubo",
"Científico loco",
"Hombre de Arena",
"Flautista de Hamelín",
"Celestial",
"Elemental de la Tierra",
"Gorgona",
"Señor de las hadas",
"Pishtaco",
"Momia",
"Cultista",
"Kaiju",
"Basilisco",
"Morlocks",
"Plaga de la muerte",
"Camión/coche fantasma",
"Dorian Gray",
"Duende",
"Espantapájaros",
"Djinn",
        };
        private static IList<string> Types = new string[] {
 "Bestia",
"Criador",
"Coleccionista",
"Destructor",
"Devorador",
"Verdugo",
"Parásito",
"Reina",
"Hechicero",
"Tentador",
"Torturador",
"Embaucador", };

        public static IList<string> Motivation = new string[] {
"Para correr en forma salvaje, destruyendo y matando",
"Dar a luz, engendrar o crear el mal",
"Robar determinados tipos de cosas",
"Provocar el fin del mundo",
"Consumir a las personas",
"Castigar a los culpables",
"Para infestar, controlar y devorar",
"Para poseer y controlar",
"Para usurpar un poder antinatural",
"Tentar a la gente para que haga el mal",
"Para herir y aterrorizar",
"Para crear el caos", }; 
        
        
        private static Random rnd = new Random();

        public static string GetLocation() =>  Location[rnd.Next(0, 99)];
        public static string GetMonster() => Monster[rnd.Next(0, 99)];
        public static string GetMonsterType() => Types[rnd.Next(0, 11)];
        public static string GetMotivation() => Motivation[rnd.Next(0, 11)];
        
    }


}
